version: "3"
services:
  tad:
    image: postgres:9.6
    container_name: "class_path"
    environment:
      - POSTGRES_DB=class_path
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5000:5432

